# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edge.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'edge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nedge.proto\x12\x04\x65\x64ge\";\n\x10InferenceRequest\x12\x13\n\x0bsensor_data\x18\x01 \x01(\x0c\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\"<\n\x11InferenceResponse\x12\x12\n\nrisk_score\x18\x01 \x01(\x02\x12\x13\n\x0b\x65xplanation\x18\x02 \x01(\t2T\n\rEdgeInference\x12\x43\n\x0ePredictAnomaly\x12\x16.edge.InferenceRequest\x1a\x17.edge.InferenceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=20
  _globals['_INFERENCEREQUEST']._serialized_end=79
  _globals['_INFERENCERESPONSE']._serialized_start=81
  _globals['_INFERENCERESPONSE']._serialized_end=141
  _globals['_EDGEINFERENCE']._serialized_start=143
  _globals['_EDGEINFERENCE']._serialized_end=227
# @@protoc_insertion_point(module_scope)
